---
# Copyright 2018 widdix GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'cfn-modules: AWS S3 bucket'
# cfn-modules:implements(ExposeArn, ExposeName, LambdaDependency)
Parameters:
  KmsKeyModule:
    Description: 'Optional but recommended stack name of kms-key module.'
    Type: String
    Default: ''
  BucketName:
    Description: 'Optional name of the bucket.'
    Type: String
    Default: ''
  Access:
    Description: 'Access policy of the bucket.'
    Type: String
    Default: Private
    AllowedValues: [Private, PublicRead, CloudFrontRead, ElbAccessLogWrite]
  Versioning:
    Description: 'Enable versioning to keep a backup if objects change.'
    Type: String
    Default: true
    AllowedValues: [true, false, 'false-but-was-true']
  NoncurrentVersionExpirationInDays:
    Description: 'Remove noncurrent object versions after days (set to 0 to disable).'
    Type: Number
    Default: 0
    MinValue: 0
  ExpirationInDays:
    Description: 'Remove objects after days (set to 0 to disable).'
    Type: Number
    Default: 0
    MinValue: 0
  # TODO add SNS event target when sns-topic module is present
  LambdaEventTargetLambdaModule1:
    Description: 'Optional stack name of lambda-function module to receive events from this S3 bucket. Also grants the Lambda function access to this bucket and this bucket access to the Lambda function.'
    Type: String
    Default: ''
  LambdaEventType1:
    Description: 'S3 bucket events you want to receive'
    Type: String
    Default: 's3:ObjectCreated:*'
  LambdaEventTargetLambdaModule2:
    Description: 'Optional stack name of lambda-function module to receive events from this S3 bucket. Also grants the Lambda function access to this bucket and this bucket access to the Lambda function.'
    Type: String
    Default: ''
  LambdaEventType2:
    Description: 'S3 bucket events you want to receive'
    Type: String
    Default: 's3:ObjectRemoved:*'
  LambdaEventTargetLambdaModule3:
    Description: 'Optional stack name of lambda-function module to receive events from this S3 bucket. Also grants the Lambda function access to this bucket and this bucket access to the Lambda function.'
    Type: String
    Default: ''
  LambdaEventType3:
    Description: 'S3 bucket events you want to receive'
    Type: String
    Default: 's3:ReducedRedundancyLostObject'
Conditions:
  HasKmsKeyModule: !Not [!Equals [!Ref KmsKeyModule, '']]
  HasPublicReadAccess: !Equals [!Ref Access, PublicRead]
  HasCloudFrontReadAccess: !Equals [!Ref Access, CloudFrontRead]
  HasElbAccessLogWriteAccess: !Equals [!Ref Access, ElbAccessLogWrite]
  HasBucketName: !Not [!Equals [!Ref BucketName, '']]
  HasVersioning: !Equals [!Ref Versioning, true]
  HadVersioning: !Equals [!Ref Versioning, 'false-but-was-true']
  HasNoncurrentVersionExpirationInDays: !Not [!Equals [!Ref NoncurrentVersionExpirationInDays, 0]]
  HasExpirationInDays: !Not [!Equals [!Ref ExpirationInDays, 0]]
  NeedsBucketPolicy: !Or [!Condition HasPublicReadAccess, !Condition HasCloudFrontReadAccess, !Condition HasKmsKeyModule, !Condition HasElbAccessLogWriteAccess]
  HasLambdaEventTargetLambdaModule1: !Not [!Equals [!Ref LambdaEventTargetLambdaModule1, '']]
  HasLambdaEventTargetLambdaModule2: !Not [!Equals [!Ref LambdaEventTargetLambdaModule2, '']]
  HasLambdaEventTargetLambdaModule3: !Not [!Equals [!Ref LambdaEventTargetLambdaModule3, '']]
Resources:
  PolicyLambdaEventTarget1:
    Type: 'AWS::IAM::Policy'
    Condition: HasLambdaEventTargetLambdaModule1
    Properties:
      Roles:
      - 'Fn::ImportValue': !Sub '${LambdaEventTargetLambdaModule1}-RoleName'
      PolicyName: !Sub 'cfn-modules-${Bucket}-target1' # ASCII characters minus the following reserved characters: backward slash (\), forward slash (/), asterisk (*), question mark (?), and white space
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - 's3:DeleteObject*'
          - 's3:GetObject*'
          - 's3:ListBucket*'
          - 's3:ListMultipartUploadParts'
          - 's3:PutObject*'
          Resource:
          - !GetAtt 'Bucket.Arn'
          - !Sub '${Bucket.Arn}/*'
  PolicyLambdaEventTarget2:
    Type: 'AWS::IAM::Policy'
    Condition: HasLambdaEventTargetLambdaModule2
    Properties:
      Roles:
      - 'Fn::ImportValue': !Sub '${LambdaEventTargetLambdaModule2}-RoleName'
      PolicyName: !Sub 'cfn-modules-${Bucket}-target2' # ASCII characters minus the following reserved characters: backward slash (\), forward slash (/), asterisk (*), question mark (?), and white space
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - 's3:DeleteObject*'
          - 's3:GetObject*'
          - 's3:ListBucket*'
          - 's3:ListMultipartUploadParts'
          - 's3:PutObject*'
          Resource:
          - !GetAtt 'Bucket.Arn'
          - !Sub '${Bucket.Arn}/*'
  PolicyLambdaEventTarget3:
    Type: 'AWS::IAM::Policy'
    Condition: HasLambdaEventTargetLambdaModule3
    Properties:
      Roles:
      - 'Fn::ImportValue': !Sub '${LambdaEventTargetLambdaModule3}-RoleName'
      PolicyName: !Sub 'cfn-modules-${Bucket}-target3' # ASCII characters minus the following reserved characters: backward slash (\), forward slash (/), asterisk (*), question mark (?), and white space
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - 's3:DeleteObject*'
          - 's3:GetObject*'
          - 's3:ListBucket*'
          - 's3:ListMultipartUploadParts'
          - 's3:PutObject*'
          Resource:
          - !GetAtt 'Bucket.Arn'
          - !Sub '${Bucket.Arn}/*'
  PermissionLambdaEventTarget1:
    Condition: HasLambdaEventTargetLambdaModule1
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: {'Fn::ImportValue': !Sub '${LambdaEventTargetLambdaModule1}-Arn'}
      Principal: 's3.amazonaws.com'
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !If [HasBucketName, !Sub 'arn:aws:s3:::${BucketName}', !Ref 'AWS::NoValue'] # least privilege only works when BucketName is set (documented limitation)
  PermissionLambdaEventTarget2:
    Condition: HasLambdaEventTargetLambdaModule2
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: {'Fn::ImportValue': !Sub '${LambdaEventTargetLambdaModule2}-Arn'}
      Principal: 's3.amazonaws.com'
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !If [HasBucketName, !Sub 'arn:aws:s3:::${BucketName}', !Ref 'AWS::NoValue'] # least privilege only works when BucketName is set (documented limitation)
  PermissionLambdaEventTarget3:
    Condition: HasLambdaEventTargetLambdaModule3
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: {'Fn::ImportValue': !Sub '${LambdaEventTargetLambdaModule3}-Arn'}
      Principal: 's3.amazonaws.com'
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !If [HasBucketName, !Sub 'arn:aws:s3:::${BucketName}', !Ref 'AWS::NoValue'] # least privilege only works when BucketName is set (documented limitation)
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !If [HasBucketName, !Ref BucketName, !Ref 'AWS::NoValue']
      LifecycleConfiguration:
        Rules:
        - AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 7
          Status: Enabled
        - NoncurrentVersionExpirationInDays: !If [HasNoncurrentVersionExpirationInDays, !Ref NoncurrentVersionExpirationInDays, 1]
          Status: !If [HasNoncurrentVersionExpirationInDays, Enabled, Disabled]
        - ExpirationInDays: !If [HasExpirationInDays, !Ref ExpirationInDays, 1]
          Status: !If [HasExpirationInDays, Enabled, Disabled]
      NotificationConfiguration:
        LambdaConfigurations:
        - !If [HasLambdaEventTargetLambdaModule1, {Event: !Ref LambdaEventType1, Function: {'Fn::ImportValue': !Sub '${LambdaEventTargetLambdaModule1}-Arn'}}, !Ref 'AWS::NoValue']
        - !If [HasLambdaEventTargetLambdaModule2, {Event: !Ref LambdaEventType2, Function: {'Fn::ImportValue': !Sub '${LambdaEventTargetLambdaModule2}-Arn'}}, !Ref 'AWS::NoValue']
        - !If [HasLambdaEventTargetLambdaModule3, {Event: !Ref LambdaEventType3, Function: {'Fn::ImportValue': !Sub '${LambdaEventTargetLambdaModule3}-Arn'}}, !Ref 'AWS::NoValue']
        # QueueConfigurations: # Using SQS as a target does not work because the SQS queue policy can not be restricted to an AWS account (only to single S3 buckets which is not possible because we don't have that information (cyclic dependency)).
      VersioningConfiguration: !If [HasVersioning, {Status: Enabled}, !If [HadVersioning, {Status: Suspended}, !Ref 'AWS::NoValue']]
      BucketEncryption: !If [HasKmsKeyModule, {ServerSideEncryptionConfiguration: [{ServerSideEncryptionByDefault: {KMSMasterKeyID: {'Fn::ImportValue': !Sub '${KmsKeyModule}-Arn'}, SSEAlgorithm: 'aws:kms'}}]}, !Ref 'AWS::NoValue']
  BucketPolicy:
    Condition: NeedsBucketPolicy
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - !If
          - HasPublicReadAccess
          - Principal: '*'
            Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub '${Bucket.Arn}/*'
          - !Ref 'AWS::NoValue'
        - !If
          - HasCloudFrontReadAccess
          - Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub '${Bucket.Arn}/*'
          - !Ref 'AWS::NoValue'
        - !If
          - HasElbAccessLogWriteAccess
          - Principal:
              AWS: # https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-logging-bucket-permissions
              - '127311923021' # us-east-1
              - '033677994240' # us-east-2
              - '027434742980' # us-west-1
              - '797873946194' # us-west-2
              - '985666609251' # ca-central-1
              - '054676820928' # eu-central-1
              - '156460612806' # eu-west-1
              - '652711504416' # eu-west-2
              - '009996457667' # eu-west-3
              - '582318560864' # ap-northeast-1
              - '600734575887' # ap-northeast-2
              - '383597477331' # ap-northeast-3
              - '114774131450' # ap-southeast-1
              - '783225319266' # ap-southeast-2
              - '718504428378' # ap-south-1
              - '507241528517' # sa-east-1
            Action: 's3:PutObject'
            Effect: Allow
            Resource: !Sub '${Bucket.Arn}/*'
          - !Ref 'AWS::NoValue'
        - !If
          - HasKmsKeyModule
          - Principal: '*'
            Action: 's3:PutObject*'
            Effect: Deny
            Resource: !Sub '${Bucket.Arn}/*'
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': ''
                's3:x-amz-server-side-encryption-aws-kms-key-id': {'Fn::ImportValue': !Sub '${KmsKeyModule}-Arn'}
          - !Ref 'AWS::NoValue'
  CloudFrontOriginAccessIdentity:
    Condition: HasCloudFrontReadAccess
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref Bucket
Outputs:
  ModuleId:
    Value: 's3-bucket'
  ModuleVersion:
    Value: '1.0.0'
  StackName:
    Value: !Ref 'AWS::StackName'
  Arn:
    Value: !GetAtt 'Bucket.Arn'
    Export:
      Name: !Sub '${AWS::StackName}-Arn'
  Name:
    Value: !Ref Bucket
    Export:
      Name: !Sub '${AWS::StackName}-Name'
  IamActions:
    Value: 's3:DeleteObject*,s3:GetObject*,s3:ListBucket*,s3:ListMultipartUploadParts,s3:PutObject*'
    Export:
      Name: !Sub '${AWS::StackName}-IamActions'
  IamResources:
    Value: !Sub '${Bucket.Arn},${Bucket.Arn}/*'
    Export:
      Name: !Sub '${AWS::StackName}-IamResources'
